name: Service A - Microservices
server:
  port: ${PORT:80}

spring:
  data:
    rest:
      base-path: /api/v1

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
  client:
    enabled: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: SEMAPHORE

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true
  OkToRetryOnAllErrors: true
  ServerListRefreshInterval: 5000
  ConnectTimeout: 5000
  ReadTimeout: 5000
  eureka:
    enabled: true

# alguns posts dizem que feign+hystrix podem conflitar no retry
#feign.hystrix.enabled=false
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=15000
#hystrix.command.default.fallback.enabled=false
#hystrix.command.default.circuitBreaker.enabled=false

#api-svcb-service:
#  ribbon:
#    ConnectTimeout: 6000
#    MaxAutoRetriesNextServer: 3
#    ReadTimeout: 6000
#    MaxAutoRetries: 3
#    OkToRetryOnAllOperations: true
#    OkToRetryOnAllErrors: true
#    ServerListRefreshInterval: 3000

logging:
  level:
    ROOT: INFO
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
        cloud:
          netflix: DEBUG
