name: Service A - Microservices
server:
  port: ${PORT:80}

spring:
  data:
    rest:
      base-path: /api/v1

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
  client:
    enabled: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

ribbon:
  ReadTimeout: 1000
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true
  OkToRetryOnAllErrors: true

#api-svcb-service:
#  ribbon:
#    ReadTimeout: 1000
#    MaxAutoRetries: 2
#    MaxAutoRetriesNextServer: 2
#    OkToRetryOnAllOperations: true
#    OkToRetryOnAllErrors: true
