name: Service B - Microservices
server:
  port: ${PORT:80}

spring:
  data:
    rest:
      base-path: /api/v1

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
  client:
    enabled: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/

ribbon:
  eureka:
    enabled: true

logging:
  level:
    ROOT: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.cloud.netflix: DEBUG
