name: Service A - Microservices
server:
  port: ${PORT:5000}

spring:
  data:
    rest:
      base-path: /api/v1

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
  client:
    enabled: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/

ribbon:
  eureka:
    enabled: true

api-svcb-service:
  ribbon:
    ConnectTimeout: 6000
    MaxAutoRetriesNextServer: 3
    ReadTimeout: 6000
    MaxAutoRetries: 3

logging:
  level:
    ROOT: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
