name: Service B - Microservices
server:
  port: ${PORT:7000}

spring:
  data:
    rest:
      base-path: /api/v1

management:
  context-path: /management

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
  client:
    enabled: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/

ribbon:
  eureka:
    enabled: true
